config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get "about", to:"pages#about"

  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get "signup", to:"users#new"

  resources :users, except: [:new]

  get "login", to:"sessions#new"
  post "login", to:"sessions#create"
  delete "logout", to:"sessions#destroy"

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum:3, maximum:120}
    validates :description, presence:true, length: {minimum:3, maximum:300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true,
                   uniqueness: true,
                   length: {minimum:3, maximum: 25}

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true,
                         uniqueness: { case_sensitive: false }, 
                         length: {minimum:3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, 
                         uniqueness: { case_sensitive: false }, 
                         length: {maximum: 105},
                         format: {with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user #double bang returns the boolean of the object.
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You need to be logged in to perform this action."
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        #@article = Article.find(params[:id])
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
        
    end

    def new
        @article = Article.new
    end

    def edit
        #@article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        #render plain: @article
        
        if @article.save
            flash[:notice] = "Article was saved successfully."
            #redirect_to article_path(@article)
            #the short version for the above line is:
            redirect_to @article
        else
            render 'new'
        end
        
    end

    def update
        #@article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        #@article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own articles."
            redirect_to @article
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to @category
    else
      render "new"
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admin users can perform that action!"
      redirect_to categories_path
    end
  
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "Your password and username did not match our system. Please try again."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out."
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def new
        @user = User.new
    end

    def edit
        
    end

    def show
        
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def update
        
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to @user
        else
            render "edit"
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the Alpha Blog, #{@user.username.capitalize}! You have successfully signed up."
            session[:user_id]= @user.id 
            redirect_to articles_path
        else
            render 'new'
        end
    end
    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "The profile and all associated articles were successfully deleted."
        redirect_to articles_path
    end

    private 
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own profile."
            redirect_to @user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow">
                    <div class="card-header font-italic">
                    <%if article.user %>
                        by <%= link_to article.user.username, user_path(article.user) %>
                    <% end %>
                    <% if article.categories.any? %>
                        <div class="mt-2">
                            <%= render article.categories %>
                        </div>
                    <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success text-decoration-none" %></h5>
                        <p class="card-text"><%= truncate(article.description, length:20, separator: " ")%></p>
                        
                        <%= link_to 'Show', article_path(article), class: "btn btn-outline-success"%>
                        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
                            <%= link_to 'Delete', article_path(article), class: "btn btn-outline-danger", data: { "turbo-method": :delete, 'turbo-confirm': 'Are you sure?' } %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(article.created_at)%> ago,
                        edited <%= time_ago_in_words(article.updated_at)%> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
        <%= render "shared/errors", obj: @article %>
    
    <div class="row justify-content-center shadow rounded bg-info p-3">
        
        <%= form_with(model: @article, data: { turbo: false }, local: true ) do |f|%>
            <div class="form-group row">
                <%= f.label :title, class: "col-2 col-form-label text-light" %>
                <div class= "col-10">
                    <%= f.text_field :title, class:"form-control shadow rounded", placeholder: "Title of article"  %>
                </div>
            </div>

            <div class="form-group row pt-3">
                <%= f.label :description, class: "col-2 col-form-label text-light" %>
                <div class= "col-10">
                    <%= f.text_area :description, rows:10, class:"form-control shadow rounded", placeholder:"Description of article" %>
                </div>
            </div>
            <div class="form-group row pt-3">
                <%= f.label :category, class: "col-2 col-form-label text-light" %>
                <div class= "col-10">
                    <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Select a Category (or leave blank)"}, 
                        {multiple: true, class:"form-select  shadow rounded"}) %>
                </div>
            </div>
            <div class="form-group row pt-3">
                <div class = "col col-2"></div>
                <div class = "col">
                    <%= f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
                
            </div>

        <% end %>
        
        
        
    </div>
    <div class="row pt-3">
        <%= link_to '[ Cancel and Return to all articles ]', articles_path, class: "text-center text-info"%>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class = "text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class = "text-center mt-4">Listing all articles.</h1>
<div class="d-flex justify-content-center">

<%= link_to "Create New Article", new_article_path, class: "text-decoration-none ml-auto p-2" %>
</div>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article'%>
<div class="flickr_pagination mb-4 mt-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class = "text-center mt-4">Create a new article</h1>
<%= render 'form'%>

app/views/articles/show.html.erb
<h2 class = "text-center mt-4"><%= @article.title %></h2>
<div class="d-flex justify-content-center">
    <%= link_to "Create New Article", new_article_path, class: "text-decoration-none ml-auto p-2" %>
</div>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow">
                <div class="card-header font-italic">
                    by <%= @article.user.username if @article.user %></br>
                        <% if @article.categories.any? %>
                            <div class="mt-2">
                                <%= render @article.categories %>
                            </div>
                        <% end %>
                </div>
                <div class="card-body">
                    <div class="card-text text-start"><%= simple_format(@article.description)%></div>
                    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                        <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
                        <%= link_to 'Delete', article_path(@article), class: "btn btn-outline-danger", data: { "turbo-method": :delete, 'turbo-confirm': 'Are you sure?' } %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(@article.created_at)%> ago,
                    edited <%= time_ago_in_words(@article.updated_at)%> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
 <%=link_to category.name, category_path(category), class: "btn btn-info rounded-pill" %>

app/views/categories/index.html.erb
<h1 class = "text-center mt-4">Categories.</h1>
<div class="container">

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>
    <% @categories.each do |category| %>
        <div class="row justify-content-md-center">
            <div class="col-4 mt-4">
                <div class="card text-center shadow">
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success text-decoration-none" %></h5>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(category.created_at)%> ago,
                        edited <%= time_ago_in_words(category.updated_at)%> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="flickr_pagination mb-4 mt-4">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class = "text-center mt-4">Add a new category</h1>
<div class="container">
        <%= render "shared/errors", obj: @category %>
    
    <div class="row justify-content-center shadow rounded bg-info p-3">
        
        <%= form_with(model: @category, data: { turbo: false }, local: true ) do |f|%>
            <div class="form-group row">
                <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
                <div class= "col-10">
                    <%= f.text_field :name, class:"form-control shadow rounded", placeholder: "Enter a name"  %>
                </div>
            </div>

            <div class="form-group row pt-3 justify-content-center">
                
                <div class="col-2">
                    <%= f.submit("Create category", class: "btn btn-outline-light btn-lg")%>
                </div>
                
            </div>

        <% end %>
        
        
        
    </div>
    <div class="row pt-3">
        <%= link_to 'Cancel', categories_path, class: "text-center text-info"%>
    </div>
</div>

app/views/categories/show.html.erb
<h1 class = "text-center mt-4"><%= @category.name.capitalize %></h1>

app/views/layouts/_footer.html.erb
<footer id = "sticky-footer" class = "py-4 bg-dark text-white mt-auto">
    <div class = "container text-center">
        Copyright &copy; Your Website
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class = "container">
  <%flash.each do |name, msg|%>
    <div class="row alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg%>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    
    <%= link_to 'ALPHA BLOG', root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a style={{ margin: 0 }} class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <%if logged_in? %>
              <li><%= link_to "Create an article", new_article_path, class:"dropdown-item" %></li>
            <% end %>
            <li><%= link_to "Show articles", articles_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a style={{ margin: 0 }} class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <%if logged_in? && current_user.admin? %>
              <li><%= link_to "Create a category", new_category_path, class:"dropdown-item" %></li>
            <% end %>
            <li><%= link_to "Show categories", categories_path, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>

      <ul class="d-flex navbar-nav mb-2 mb-lg-0">
        <%if logged_in? %>
          <li class="nav-item dropdown">
            <a style={{ margin: 0 }} class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username.capitalize %> <%= "(Admin)" if current_user.admin? %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile page", user_path(current_user), class:"dropdown-item" %></li>
              <li><%= link_to "Edit profile", edit_user_path(current_user), class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Delete profile", user_path(current_user), class:"dropdown-item text-danger", data: { "turbo-method": :delete, 'turbo-confirm': 'Are you sure?' } %></li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link",  data: { "turbo-method": :delete, 'turbo-confirm': 'Are you sure?' }%>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", signup_path, class: "nav-link" %>
          </li>
        <%end%>
      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%=render 'layouts/navigation'%>
    <div class = "container" id = "page-content">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About me and my blog.</h1>

<p>Thanks for visiting.</p>
<ul>
<li>Personal life</li>
<li>Gear I use</li>
<li>Contact details</li>
</ul>

app/views/pages/home.html.erb
<div class="container">
    <div class="mt-4 mb-4 p-5 bg-primary text-white text-center rounded" id = "home-container">
        <h1>ALPHA BLOG</h1>
        <hr class = "my-4">
        <p>Lorem ipsum...</p>
        <p>Lorem ipsum...</p>
        <p>Lorem ipsum...</p>
        <p>Lorem ipsum...</p>
        
        <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <ul>
            <% obj.errors.full_messages.each do |m| %>
                <li><%=m%></li>
            <% end%>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
        <%= render "shared/errors", obj: @user %>
    
    <div class="row justify-content-center shadow rounded bg-info p-3">
        
        <%= form_with(model: @user, data: { turbo: false }, local: true ) do |f|%>
            <div class="form-group row">
                <%= f.label :username, class: "col-2 col-form-label text-light" %>
                <div class= "col-10">
                    <%= f.text_field :username, class:"form-control shadow rounded", placeholder: "Enter a username"  %>
                </div>
            </div>

            <div class="form-group row pt-3">
                <%= f.label :email, class: "col-2 col-form-label text-light" %>
                <div class= "col-10">
                    <%= f.email_field :email, class:"form-control shadow rounded", placeholder:"Enter your email address" %>
                </div>
            </div>

            <div class="form-group row pt-3">
                <%= f.label :password, class: "col-2 col-form-label text-light" %>
                <div class= "col-10">
                    <%= f.password_field :password, class:"form-control shadow rounded", placeholder: "Choose a password"  %>
                </div>
            </div>


            <div class="form-group row pt-3 justify-content-center">
                
                <div class="col-2">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg")%>
                </div>
                
            </div>

        <% end %>
        
        
        
    </div>
    <div class="row pt-3">
        <%= link_to '[ Cancel and Return to all articles ]', articles_path, class: "text-center text-info"%>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class = "text-center mt-4">Edit your profile</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1 class = "text-center mt-4">Alpha Bloggers</h1>
</div>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
<div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow">
                    <div class="card-header font-italic">
                        <%= link_to user.username, user %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Profile image</h5>
                        <img src="..." alt=<%= user.username+"'s avatar" %> class="img-thumbnail">
                        <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                        
                        <%= link_to 'View profile', user, class: "btn btn-outline-success"%>
                        <% if logged_in? %>
                            <% if user == current_user %>
                                <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info" %>
                            <% end %>
                            <% if current_user.admin? %>
                                <%= link_to 'Delete profile', user_path(user), class: "btn btn-outline-danger", data: { "turbo-method": :delete, 'turbo-confirm': 'Are you sure?' } %>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Joined <%= time_ago_in_words(user.created_at)%> ago </small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>
</div>
<div class="flickr_pagination mb-4 mt-2">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class = "text-center mt-4">Sign up for Alpha Blog</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 class = "text-center mt-4"><%= @user.username.capitalize %>'s profile</h1>

<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info " %>
    </div>
<% end %>

<h3 class = "text-center mt-4">Articles</h3>
</div>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/article' %>
</div>
<div class="flickr_pagination mb-4 mt-2>
    <%= will_paginate @articles, :container => false %>
</div>